### PR TITLE
Mem ctrl

### PR DESCRIPTION
**Pull request by mara-kr**
BRAM part of memory controller

### CODE REVIEW

**Review by ryanovsky — APPROVED** [review]

**Comment by Sirius285** [comment]
Graphics needs individual ports exposed for VRAM_A/B/C (since OBJ processing and BG processing need to access VRAM simultaneously), and individual ports to the BG palette RAM and the OBJ palette RAM.

**Comment by ryanovsky** [comment]
:+1:

**Comment by ryanovsky** [comment]
:+1:

**Comment by Sirius285** [comment]
:+1:

**Pull request merged**
